# Generated by Django 3.1.3 on 2022-01-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220131_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshistory',
            name='obj_file',
            field=models.TextField(blank=True),
        ),
    ]
