# Generated by Django 3.1.3 on 2022-01-31 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_jobshistory_obj_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobshistory',
            old_name='job_initiated_on',
            new_name='initiated_on',
        ),
        migrations.AddField(
            model_name='jobshistory',
            name='completed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='jobshistory',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
