# Generated by Django 3.1.3 on 2022-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220131_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobshistory',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='jobshistory',
            name='complete_status',
            field=models.IntegerField(default=0),
        ),
    ]
