# Generated by Django 3.1.3 on 2022-02-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20220202_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshistory',
            name='remove_status',
            field=models.IntegerField(default=0),
        ),
    ]
